---
- hosts: [mesos_primaries]
  sudo: True
  pre_tasks:
    - name: Install HAProxy (RedHat)
      yum: pkg=haproxy state=present
      when: ansible_os_family == "RedHat"
    - name: Install HAProxy (Ubuntu)
      apt: pkg=haproxy state=present
      when: ansible_os_family == "Debian"
    - name: Sets haproxy to enabled (Ubuntu)
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
      when: ansible_os_family == "Debian"
  roles:
    - { role: 'ansible-java8', tags: ['runtimes', 'java'], when: ansible_os_family == 'Debian' }
    - { role: 'ansible-zookeeper', zookeeper_hosts: "{{ groups.mesos_primaries}}", tags: ['zookeeper'] }
    - { role: 'ansible-mesos', mesos_quorum: "2", zookeeper_hostnames: "{{ groups.mesos_primaries | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}", mesos_install_mode: 'master', mesos_cluster_name: 'mlh_mesos', tags: ['mesos', 'platforms'] }
    - { role: 'greendayonfire.mongodb', tags: ['mongodb'] }
  vars:
    mongodb_conf_bind_ip: 0.0.0.0
    mongodb_conf_auth: true
    mongodb_conf_replSet: myrs
    mongodb_replication_params:
      - { host_name: <interal_ip1>, host_port: "{{ mongodb_conf_port }}", host_type: replica }
      - { host_name: <interal_ip1>, host_port: "{{ mongodb_conf_port }}", host_type: replica }
      - { host_name: <interal_ip1>, host_port: "{{ mongodb_conf_port }}", host_type: replica }
    mongodb_user_admin_name: siteUserAdmin
    mongodb_user_admin_password: passw0rd
    mongodb_root_admin_name: siteRootAdmin
    mongodb_root_admin_password: passw0rd
    mongodb_users:
      - {
        name: username,
        password: passw0rd,
        roles: readWrite,
        database: recognition
      }
      - {
        name: username,
        password: passw0rd,
        roles: read,
        database: recognition
      }
    # generate keyfile content with 'openssl rand -base64 741' on one of the servers
    mongodb_keyfile_content: |
      8pYcxvCqoe89kcp33KuTtKVf5MoHGEFjTnudrq5BosvWRoIxLowmdjrmUpVfAivh
      CHjqM6w0zVBytAxH1lW+7teMYe6eDn2S/O/1YlRRiW57bWU3zjliW3VdguJar5i9
      Z+1a8lI+0S9pWynbv9+Ao0aXFjSJYVxAm/w7DJbVRGcPhsPmExiSBDw8szfQ8PAU
      2hwRl7nqPZZMMR+uQThg/zV9rOzHJmkqZtsO4UJSilG9euLCYrzW2hdoPuCrEDhu
      Vsi5+nwAgYR9dP2oWkmGN1dwRe0ixSIM2UzFgpaXZaMOG6VztmFrlVXh8oFDRGM0
      cGrFHcnGF7oUGfWnI2Cekngk64dHA2qD7WxXPbQ/svn9EfTY5aPw5lXzKA87Ds8p
      KHVFUYvmA6wVsxb/riGLwc+XZlb6M9gqHn1XSpsnYRjF6UzfRcRR2WyCxLZELaqu
      iKxLKB5FYqMBH7Sqg3qBCtE53vZ7T1nefq5RFzmykviYP63Uhu/A2EQatrMnaFPl
      TTG5CaPjob45CBSyMrheYRWKqxdWN93BTgiTW7p0U6RB0/OCUbsVX6IG3I9N8Uqt
      l8Kc+7aOmtUqFkwo8w30prIOjStMrokxNsuK9KTUiPu2cj7gwYQ574vV3hQvQPAr
      hhb9ohKr0zoPQt31iTj0FDkJzPepeuzqeq8F51HB56RZKpXdRTfY8G6OaOT68cV5
      vP1O6T/okFKrl41FQ3CyYN5eRHyRTK99zTytrjoP2EbtIZ18z+bg/angRHYNzbgk
      lc3jpiGzs1ZWHD0nxOmHCMhU4usEcFbV6FlOxzlwrsEhHkeiununlCsNHatiDgzp
      ZWLnP/mXKV992/Jhu0Z577DHlh+3JIYx0PceB9yzACJ8MNARHF7QpBkhtuGMGZpF
      T+c73exupZFxItXs1Bnhe3djgE3MKKyYvxNUIbcTJoe7nhVMrwO/7lBSpVLvC4p3
      wR700U0LDaGGQpslGtiE56SemgoP

